language: c
os:
  - linux
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev
install:
  - curl -O https://www.libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - (cd SDL2-2.0.5 && ./configure && make && sudo make install)
script:
  - mkdir build
  - cd build
  - cmake .. && make
